with open('config.py', 'w', encoding='utf-8') as f:
    f.write('TICKERS = ["SPY", "TLT", "GLD", "QQQ", "BTC-USD"]\n')
    f.write('\n')
    f.write('TICKER_LABELS = {\n')
    f.write('    "SPY": "SPY (US Equity)",\n')
    f.write('    "TLT": "TLT (Long Bond)",\n')
    f.write('    "GLD": "GLD (Gold)",\n')
    f.write('    "QQQ": "QQQ (Nasdaq)",\n')
    f.write('    "BTC-USD": "BTC (Bitcoin)",\n')
    f.write('}\n')
    f.write('\n')
    f.write('DEFAULT_START = "2018-01-01"\n')
    f.write('DEFAULT_END = "2024-12-31"\n')
    f.write('N_SIM = 50000\n')
    f.write('CONFIDENCE = 0.99\n')
    f.write('CACHE_DIR = "data/cache"\n')
print("Done")